# Generated by Django 4.2.23 on 2025-07-17 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('COW', 'Cow'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('CHICKEN', 'Chicken'), ('PIG', 'Pig')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='animals_for_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.animal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('FARMER', 'Farmer')], default='BUYER', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'animal')},
        ),
    ]
